//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludique.Nimbus.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ludique.Nimbus.Web.Resources.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user,
        ///
        ///Your account has been successfully confirmed.
        ///
        ///Cordially,
        ///The Ludique Team.
        /// </summary>
        internal static string AccountConfirmed_Body {
            get {
                return ResourceManager.GetString("AccountConfirmed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Is Confirmed.
        /// </summary>
        internal static string AccountConfirmed_Subject {
            get {
                return ResourceManager.GetString("AccountConfirmed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our application!
        ///
        ///Please click on the link below to activate your account:
        ///{baseUrl}/confirm?id={id}&amp;token={token}
        ///
        ///Cordially,
        ///The Ludique Team.
        /// </summary>
        internal static string AccountCreation_Body {
            get {
                return ResourceManager.GetString("AccountCreation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Your Account.
        /// </summary>
        internal static string AccountCreation_Subject {
            get {
                return ResourceManager.GetString("AccountCreation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user,
        ///It seems you have lost your password...
        ///
        ///In this case, please click on the link below to reset it:
        ///{baseUrl}/confirm?id={id}&amp;token={token}
        ///
        ///If we&apos;ve been mistaken, we suggest you to delete this message.
        ///
        ///Cordially,
        ///The Ludique Team.
        /// </summary>
        internal static string PasswordRecovery_Body {
            get {
                return ResourceManager.GetString("PasswordRecovery_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        internal static string PasswordRecovery_Subject {
            get {
                return ResourceManager.GetString("PasswordRecovery_Subject", resourceCulture);
            }
        }
    }
}
